In [1]:
import pandas as pd
import numpy as np
import random
import math
np.random.seed(1)
scale = 1/max(1., (2+2)/2.)
limit = math.sqrt(3.0 * scale)

dat = pd.read_csv('./data/genres.csv')
tot = np.array(dat)

movies = np.array([200,211,113,233,112,443,12,65])
x = np.array(dat)
X = tot[movies,:]
m , n = X.shape
y = np.ones((m,1))

In [2]:
import scipy.optimize as op

def Sigmoid(z):
    return 1/(1 + np.exp(-z));

def Gradient(theta,x,y):
    m , n = x.shape
    theta = theta.reshape((n,1));
    y = y.reshape((m,1))
    sigmoid_x_theta = Sigmoid(x.dot(theta));
    grad = ((x.T).dot(sigmoid_x_theta-y))/m;
    return grad.flatten();

def CostFunc(theta,x,y):
    m,n = x.shape; 
    theta = theta.reshape((n,1));
    y = y.reshape((m,1));
    term1 = np.log(Sigmoid(x.dot(theta)));
    term2 = np.log(1-Sigmoid(x.dot(theta)));
    term1 = term1.reshape((m,1))
    term2 = term2.reshape((m,1))
    term = y * term1 + (1 - y) * term2;
    J = -((np.sum(term))/m);
    return J;

# intialize X and y
#X = np.array([[1,2,3],[1,3,4]]);
#y = np.array([[1],[0]]);

initial_theta = np.random.uniform(-limit, limit, size=(n))
Result = op.minimize(fun = CostFunc, x0 = initial_theta, args = (X, y),method = 'TNC',jac = Gradient);
optimal_theta = Result.x;
optimal_theta

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:19: RuntimeWarning: divide by zero encountered in log
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:22: RuntimeWarning: invalid value encountered in multiply

array([16.69565109, 12.783396  ,  3.78338103,  0.82454859,  5.71723028,
       -0.99856243, -0.76850239, -0.37829741,  5.06450841])

Action,Adventure,Fantasy,Sci-fi,Thriller,Comedy,Romance,Horror,Animation

In [3]:
m_dat = pd.read_csv('./data/movie_metadata_edited.csv')
m_names = m_dat['movie_title']
m_genres = m_dat[['genres']]
m_dat.iloc[movies,[1,2]]

,genres,movie_title
200,Action|Crime|Thriller,Fast Five
211,Adventure|Drama|Fantasy,Life of Pi
113,Action|Drama,Hancock
233,Adventure|Drama|Sci-Fi|Thriller,Gravity
112,Adventure|Family|Fantasy|Mystery,Harry Potter and the Goblet of Fire
443,Adventure|Animation|Family|Western,Spirit: Stallion of the Cimarron
12,Action|Adventure|Fantasy,Pirates of the Caribbean: Dead Man's Chest
65,Action|Crime|Drama|Thriller,The Dark Knight

In [4]:
res = (x@optimal_theta)
ans = np.argsort(res)
ans = np.flip(ans)
print(res[ans[:20]])
m_dat.iloc[ans[:20],[1,2]]

[39.80420698 39.80420698 39.80420698 39.80420698 39.80420698 39.80420698
 39.42590957 39.15148511 38.97965839 38.97965839 38.97965839 38.97965839
 38.60136098 38.38298271 38.32693652 38.32693652 38.15292268 37.98109596
 37.32837409 37.32837409]

,genres,movie_title
33,Action|Adventure|Fantasy|Sci-Fi|Thriller,X-Men: The Last Stand
120,Action|Adventure|Fantasy|Sci-Fi|Thriller,X-Men Origins: Wolverine
720,Action|Adventure|Fantasy|Sci-Fi|Thriller,Reign of Fire
885,Action|Adventure|Family|Fantasy|Sci-Fi|Thriller,Race to Witch Mountain
199,Action|Adventure|Fantasy|Sci-Fi|Thriller,X-Men 2
46,Action|Adventure|Fantasy|Sci-Fi|Thriller,X-Men: Days of Future Past
632,Action|Adventure|Fantasy|Horror|Sci-Fi|Thriller,Blade: Trinity
342,Action|Adventure|Animation|Family|Fantasy|Sci-Fi,Atlantis: The Lost Empire
690,Action|Adventure|Fantasy|Thriller,The Scorpion King
303,Action|Adventure|Fantasy|Thriller,The Mummy Returns
316,Action|Adventure|Fantasy|Thriller,Lara Croft: Tomb Raider
452,Action|Adventure|Family|Fantasy|Thriller,Mighty Joe Young
71,Action|Adventure|Fantasy|Horror|Thriller,The Mummy: Tomb of the Dragon Emperor
160,Action|Adventure|Animation|Fantasy|Romance|Sci-Fi,Final Fantasy: The Spirits Within
293,Action|Adventure|Animation|Family|Fantasy,Legend of the Guardians: The Owls of Ga'Hoole
146,Action|Adventure|Animation|Fantasy,Beowulf
129,Action|Adventure|Animation|Comedy|Family|Fanta...,G-Force
457,Action|Adventure|Comedy|Fantasy|Thriller,The Brothers Grimm
181,Action|Adventure|Animation|Comedy|Family|Fantasy,Puss in Boots
583,Action|Adventure|Animation|Comedy|Crime|Family...,Osmosis Jones

In [5]:
def find_com_words (name, words):
    count = 0
    for word in words:
        if (word not in ['The','the','of','Of','at','At','a','Z','and','And','A','in','In','on','On']):
            if(name.find(word)!=-1) :
                count = count +1
    #print(count)
    if(count >=2):
        return True
    else :
        return False

In [6]:
name_class = []
for test in m_names[movies]:
    words = test.split()
    #print(words)
    i = 0
    for name in m_names:
        if(find_com_words(name,words)):
            #print(name,i) 
            if(i not in movies):
                name_class.append(i)
        i = i+1
        
name_class = np.array(name_class)     
m_dat.iloc[name_class,[1,2]]

,genres,movie_title
8,Adventure|Family|Fantasy|Mystery,Harry Potter and the Half-Blood Prince
111,Adventure|Family|Fantasy|Mystery,Harry Potter and the Order of the Phoenix
185,Adventure|Family|Fantasy|Mystery,Harry Potter and the Prisoner of Azkaban
188,Action|Fantasy,Harry Potter and the Deathly Hallows: Part II
191,Adventure|Family|Fantasy,Harry Potter and the Sorcerer's Stone
195,Fantasy,Harry Potter and the Deathly Hallows: Part I
268,Adventure|Family|Fantasy|Mystery,Harry Potter and the Chamber of Secrets
1,Action|Adventure|Fantasy,Pirates of the Caribbean: At World's End
17,Action|Adventure|Fantasy,Pirates of the Caribbean: On Stranger Tides
194,Action|Adventure|Fantasy,Pirates of the Caribbean: The Curse of the Bla...
3,Action|Thriller,The Dark Knight Rises